services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: ptax
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.9.2-python3.11
    depends_on: [postgres]
    environment:
      &airflow-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/ptax
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:2.9.2-python3.11
    depends_on: [postgres, airflow-webserver]
    environment: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./scripts:/opt/airflow/scripts
    command: ["scheduler"]
  airflow-init:
    image: apache/airflow:2.9.2-python3.11
    depends_on:
      - postgres
    environment: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./scripts:/opt/airflow/scripts
    entrypoint: ["bash", "-c"]
    command:
      - |
        airflow db init &&
        airflow users create \
          --username airflow \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password airflow


volumes:
  postgres_data:
